development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url:  postgres://amixamyqozjrui:334fb5a61dbe1b1189b0a2065f1d9399239f9542dfea91536890b8771c1dcbad@ec2-184-73-199-72.compute-1.amazonaws.com:5432/d6ho9c03qedugp


